<?php

return [
    [
        'trans_id' => '325229570',
        'trans_user_id' => '1194398',
        'trans_plaid_trans_id' => 'MMrwv4gA3eTr3EBka0eZSZEzyERXAQfqKveKy',
        'trans_plaid_categories' => 'Shops,Convenience Stores',
        'trans_plaid_amount' => '1.06',
        'trans_plaid_category_id' => '19015000',
        'trans_plaid_date' => '2022-11-23',
        'trans_plaid_name' => 'Circle K',
        'type' => 'debit',
    ],
    [
        'trans_id' => '325229571',
        'trans_user_id' => '1194398',
        'trans_plaid_trans_id' => '9kKzY5D9ZVfyzdagrE7BHBQVKQkwjRtR9vD98',
        'trans_plaid_categories' => 'Travel,Gas Stations',
        'trans_plaid_amount' => '15.25',
        'trans_plaid_category_id' => '22009000',
        'trans_plaid_date' => '2022-11-25',
        'trans_plaid_name' => 'Zip.Co* Quadpay Anywhe',
        'type' => 'credit',
    ],
    [
        'trans_id' => '325229572',
        'trans_user_id' => '1194398',
        'trans_plaid_trans_id' => '7yNnY86gJ7hMR5rpA98ztLMgvMA5ZJCRnbjnE',
        'trans_plaid_categories' => 'Travel,Gas Stations',
        'trans_plaid_amount' => '46.00',
        'trans_plaid_category_id' => '22009000',
        'trans_plaid_date' => '2022-11-25',
        'trans_plaid_name' => 'Wawa',
        'type' => 'debit',
    ],
    [
        'trans_id' => '325229573',
        'trans_user_id' => '1194398',
        'trans_plaid_trans_id' => 'VLyvZEgA4eS6pe5J7QNOSNep5e9D3aH8MPwMK',
        'trans_plaid_categories' => 'Shops,Discount Stores',
        'trans_plaid_amount' => '4.10',
        'trans_plaid_category_id' => '19020000',
        'trans_plaid_date' => '2022-11-25',
        'trans_plaid_name' => 'Dollar General',
        'type' => 'credit',
    ],
    [
        'trans_id' => '325229574',
        'trans_user_id' => '1194398',
        'trans_plaid_trans_id' => 'b01vyQLKV3T5YNjEBM0XIL0em0VPzaCLzkwzd',
        'trans_plaid_categories' => 'Shops,Pets',
        'trans_plaid_amount' => '40.44',
        'trans_plaid_category_id' => '19042000',
        'trans_plaid_date' => '2022-11-26',
        'trans_plaid_name' => 'Petco',
        'type' => 'debit',
    ],
    [
        'trans_id' => '325229575',
        'trans_user_id' => '1194398',
        'trans_plaid_trans_id' => 'gxg90EBAwvSAZX8gPnQzHmXnYXek7MTOjrLjA',
        'trans_plaid_categories' => 'Shops,Pets',
        'trans_plaid_amount' => '36.18',
        'trans_plaid_category_id' => '19042000',
        'trans_plaid_date' => '2022-11-26',
        'trans_plaid_name' => 'Petco',
        'type' => 'credit',
    ],
    [
        'trans_id' => '325229576',
        'trans_user_id' => '1194398',
        'trans_plaid_trans_id' => '5B5eYmdEabiP5y0ZmOXwC5jJdjnXwocRnr9n6',
        'trans_plaid_categories' => 'Transfer,Withdrawal,ATM',
        'trans_plaid_amount' => '110.00',
        'trans_plaid_category_id' => '21012002',
        'trans_plaid_date' => '2023-01-01',
        'trans_plaid_name' => 'ATM Withdrawal',
        'type' => 'debit',
    ]
];
